export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';
export const GET_PROPERTY_COMMENTS_SUCCESS = 'GET_PROPERTY_COMMENTS_SUCCESS';
export const GET_PROPERTY_BY_ID_SUCCESS = 'GET_PROPERTY_BY_ID_SUCCESS';
export const ADD_PROPERTY_COMMENT_SUCCESS = 'ADD_PROPERTY_COMMENT_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SET_USER_TYPE_SUCCESS = 'USER_TYPE_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
