export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';
export const GET_PROPERTY_COMMENTS_SUCCESS = 'GET_PROPERTY_COMMENTS_SUCCESS';
export const GET_PROPERTY_BY_ID_SUCCESS = 'GET_PROPERTY_BY_ID_SUCCESS';
export const ADD_PROPERTY_COMMENT_SUCCESS = 'ADD_PROPERTY_COMMENT_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
